/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CarrosController;
import controller.ClienteController;
import javax.persistence.spi.PersistenceUnitTransactionType;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aprovacao;
import model.Carros;
import model.Clientes;

/**
 *
 * @author Alana
 */
public class ClienteView extends javax.swing.JFrame {
    DefaultTableModel model;
    Clientes clente;
    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
        loadtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnovo = new javax.swing.JButton();
        bteditar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Agencia", "Conta", "Aprovação", "Cpf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        bteditar.setText("Editar");
        bteditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditarActionPerformed(evt);
            }
        });

        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        jButton1.setText("Atualiza");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Menu Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bteditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btexcluir)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btexcluir)
                    .addComponent(bteditar)
                    .addComponent(btnovo)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        // TODO add your handling code here:
        NovoCliente novo = new NovoCliente();
        novo.setVisible(true);
    }//GEN-LAST:event_btnovoActionPerformed

    private void bteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditarActionPerformed
        // TODO add your handling code here:
         int i [] = jTable1.getSelectedRows();
        if(i.length == 0){
            JOptionPane.showMessageDialog(null, "Selecione um contato");
        }else if (i.length > 1){
            JOptionPane.showMessageDialog(null, "Selecione apenas um contato");
        }else{
            Clientes cliente = new Clientes();
            cliente.setAgencia((String) jTable1.getValueAt(i[0], 2));
//            cliente.setAprovacao((Aprovacao) jTable1.getValueAt(i[0], 4));
            cliente.setConta((String) jTable1.getValueAt(i[0], 3));
            cliente.setCpf(NovoCliente.format((String) jTable1.getValueAt(i[0], 5)));
            cliente.setId((int) jTable1.getValueAt(i[0], 0));
            cliente.setNome((String) jTable1.getValueAt(i[0], 1));
        NovoCliente cli = new NovoCliente(model, cliente);
        cli.setVisible(true);
        
        }
    }//GEN-LAST:event_bteditarActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        // TODO add your handling code here:
        int i [] = jTable1.getSelectedRows();
        if(i.length == 0){
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }else if (i.length > 1){
            JOptionPane.showMessageDialog(null, "Selecione apenas um cliente");
        }else{
        Clientes cliente = new Clientes();
              
        
         cliente.setId((int) jTable1.getValueAt(i[0], 0));
         cliente.setNome((String) jTable1.getValueAt(i[0], 1));
       
        int resposta = JOptionPane.showConfirmDialog(null, "Dejesa excluir "+ cliente.getNome()+" ?");
            if (resposta == 0){
                if(new ClienteController().remover(cliente.getId())){
                JOptionPane.showMessageDialog(null, "cliente excluido com sucesso!");
                loadtable();}
        }else{
            JOptionPane.showMessageDialog(null, "Falha ao tentar excluir");
            }
        }
    }//GEN-LAST:event_btexcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadtable();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        ClienteView.this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bteditar;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
public  void loadtable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(Clientes cliente: new ClienteController().listar(null)){
        model.addRow(new Object[]{cliente.getId(),cliente.getNome(), cliente.getAgencia(), cliente.getConta(), cliente.getAprovacao().getAprovacao().toUpperCase(),NovoCliente.format(cliente.getCpf())});
            
        }
    
    }



}
