/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CarrosController;
import dao.CorDAO;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Carros;
import model.Cores;

/**
 *
 * @author a9211062
 */
public class NovoCarros extends javax.swing.JFrame {
    Carros car;
    
    /**
     * Creates new form NovoCarros
     */
    public NovoCarros() {
        initComponents();
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taObs = new javax.swing.JTextArea();
        tfRenavam = new javax.swing.JTextField();
        tfAnomodelo = new javax.swing.JTextField();
        tfplaca = new javax.swing.JTextField();
        tfchassi = new javax.swing.JTextField();
        tfmodelo = new javax.swing.JTextField();
        tfanofabricacao = new javax.swing.JTextField();
        tfmotorizacao = new javax.swing.JTextField();
        lbRenavam = new javax.swing.JLabel();
        lbPlaca = new javax.swing.JLabel();
        lbChassi = new javax.swing.JLabel();
        lbAnomodelo = new javax.swing.JLabel();
        lbAnofabricacao = new javax.swing.JLabel();
        cbCores = new javax.swing.JComboBox();
        lbModelo = new javax.swing.JLabel();
        lbMotorizacao = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();

        setTitle("Novo Carro");
        setResizable(false);

        taObs.setColumns(20);
        taObs.setRows(5);
        jScrollPane1.setViewportView(taObs);

        tfRenavam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRenavamActionPerformed(evt);
            }
        });

        tfplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfplacaActionPerformed(evt);
            }
        });

        tfchassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfchassiActionPerformed(evt);
            }
        });

        tfmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmodeloActionPerformed(evt);
            }
        });

        lbRenavam.setText("Renavam");

        lbPlaca.setText("Placa");

        lbChassi.setText("Chassi");

        lbAnomodelo.setText("Ano Modelo");

        lbAnofabricacao.setText("Ano Fabricação");

        cbCores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma cor", "Azul", "Branco", "Cinza", "Preto" }));
        cbCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCoresActionPerformed(evt);
            }
        });

        lbModelo.setText("Modelo");

        lbMotorizacao.setText("Motorização");

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        jLabel1.setText("Observações");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRenavam)
                            .addComponent(lbPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbChassi)
                            .addComponent(lbModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfchassi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbAnofabricacao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfanofabricacao))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbAnomodelo)
                                    .addGap(28, 28, 28)
                                    .addComponent(tfAnomodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbMotorizacao)
                                    .addGap(26, 26, 26)
                                    .addComponent(tfmotorizacao)))
                            .addComponent(cbCores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRenavam)
                    .addComponent(lbAnomodelo)
                    .addComponent(tfRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnomodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfanofabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAnofabricacao)
                    .addComponent(tfplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfmotorizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMotorizacao)
                    .addComponent(lbChassi)
                    .addComponent(tfchassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbModelo)
                    .addComponent(tfmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfRenavamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRenavamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRenavamActionPerformed

    private void tfplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfplacaActionPerformed

    private void tfchassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfchassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfchassiActionPerformed

    private void tfmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmodeloActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        if (tfRenavam.getText().equals("")||tfanofabricacao.getText().equals("")||tfAnomodelo.getText().equals("")||tfchassi.getText().equals("")||tfplaca.getText().equals("")||tfmotorizacao.getText().equals("")||tfmodelo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencher todos os campos obrigatorios");
        }else{
            CarrosController control = new CarrosController();
            CorDAO dao = new CorDAO();
            Cores cor = new Cores();
           
            if(car == null){
                       
                        System.out.println(dao.select(cbCores.getSelectedIndex()));
                    if(control.adicionar(tfRenavam.getText(), tfchassi.getText(),Integer.parseInt(tfanofabricacao.getText()), Integer.parseInt(tfAnomodelo.getText()), tfmodelo.getText(), 
                        tfmotorizacao.getText(),tfplaca.getText() ,dao.select(cbCores.getSelectedIndex()) , taObs.getText())){
                    
                    JOptionPane.showMessageDialog(null, "Carro adicionado com sucesso");
                    
                    limpar();               
                }else{
                       
                JOptionPane.showMessageDialog(null, "Erro ao adicionar"+ cbCores.getSelectedIndex());
                }
            }else{
                if(control.atualizar(car.getId(), tfRenavam.getText(), Integer.parseInt(tfanofabricacao.getText()), Integer.parseInt(tfAnomodelo.getText()),tfchassi.getText(), tfmotorizacao.getText(), taObs.getText(), tfmodelo.getText())){
                
                }else{
                JOptionPane.showMessageDialog(null, "Erro ao Editar");
                }
            
            }
        
        }       
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        NovoCarros.this.setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void cbCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCoresActionPerformed
       
    }//GEN-LAST:event_cbCoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btNovo;
    private javax.swing.JComboBox cbCores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAnofabricacao;
    private javax.swing.JLabel lbAnomodelo;
    private javax.swing.JLabel lbChassi;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbMotorizacao;
    private javax.swing.JLabel lbPlaca;
    private javax.swing.JLabel lbRenavam;
    private javax.swing.JTextArea taObs;
    private javax.swing.JTextField tfAnomodelo;
    private javax.swing.JTextField tfRenavam;
    private javax.swing.JTextField tfanofabricacao;
    private javax.swing.JTextField tfchassi;
    private javax.swing.JTextField tfmodelo;
    private javax.swing.JTextField tfmotorizacao;
    private javax.swing.JTextField tfplaca;
    // End of variables declaration//GEN-END:variables
    
    private void limpar(){
    tfAnomodelo.setText("");
    tfRenavam.setText("");
    tfanofabricacao.setText("");
    tfchassi.setText("");
    tfmodelo.setText("");
    tfmotorizacao.setText("");
    tfplaca.setText("");
    taObs.setText("");
    cbCores.setSelectedIndex(0);
    }
    
}
