/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import dao.AprovacaoDAO;
import dao.ClienteDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aprovacao;
import model.Clientes;

/**
 *
 * @author Alana
 */
public class NovoCliente extends javax.swing.JFrame {
    Clientes clientes;
    DefaultTableModel model;
    /**
     * Creates new form NovoCliente
     */
    public NovoCliente() {
        initComponents();
    }
    public NovoCliente(DefaultTableModel model, Clientes cliente){
        this.model = model;
        this.clientes = cliente;
        initComponents();
        cliente.getId();
        tfnome.setText(cliente.getNome());
        tfagencia.setText(cliente.getAgencia());
        tfconta.setText(cliente.getConta());
        formcpf.setText(cliente.getCpf());
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        lbnome = new javax.swing.JLabel();
        tfnome = new javax.swing.JTextField();
        lbcpf = new javax.swing.JLabel();
        formcpf = new javax.swing.JFormattedTextField();
        lbagencia = new javax.swing.JLabel();
        lbconta = new javax.swing.JLabel();
        lbapr = new javax.swing.JLabel();
        tfagencia = new javax.swing.JTextField();
        tfconta = new javax.swing.JTextField();
        btsalvar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jRadioButton2.setText("jRadioButton2");

        setResizable(false);

        lbnome.setText("Nome");

        lbcpf.setText("Cpf");

        try {
            formcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formcpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lbagencia.setText("Agencia");

        lbconta.setText("Conta");

        lbapr.setText("Aprovação");

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Aprovado", "Não aprovado", "Sem consulta" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbcpf)
                        .addGap(18, 18, 18)
                        .addComponent(formcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbapr)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(167, 167, 167))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbnome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbagencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfagencia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btsalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btcancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbconta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfconta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcpf)
                    .addComponent(formcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbagencia)
                    .addComponent(lbconta)
                    .addComponent(tfagencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbapr)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar)
                    .addComponent(btcancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
        Clientes cli = new Clientes();
        ClienteController control = new ClienteController();
        AprovacaoDAO dao = new AprovacaoDAO();
    ClienteDAO daos = new ClienteDAO();
        cli = daos.select(clientes.getId());
         System.out.println(clientes.toString());
        if(tfnome.getText().equals("")||tfagencia.getText().equals("")||tfconta.getText().equals("")||formcpf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        
        }else{
            if(clientes == null){
            
                if(control.adicionar(tfnome.getText(),NovoCliente.clear( formcpf.getText()), tfagencia.getText(), tfconta.getText(), dao.select(jComboBox1.getSelectedIndex()))){
                    
                    JOptionPane.showMessageDialog(null, "Cliente adicionado com sucesso");
                }else{JOptionPane.showMessageDialog(null, "Erro ao adicionar");}
                    
                    
        }
        
       
        else{
            if(control.atualizar(clientes.getId(), tfnome.getText(), tfagencia.getText(), tfconta.getText(), dao.select(jComboBox1.getSelectedIndex()))){
            JOptionPane.showMessageDialog(null, "Cliente atualizado");
            }else{
            JOptionPane.showMessageDialog(null, "Erro ao editar");
            }
        
        }
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        // TODO add your handling code here:
        NovoCliente.this.setVisible(false);
    }//GEN-LAST:event_btcancelarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JFormattedTextField formcpf;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lbagencia;
    private javax.swing.JLabel lbapr;
    private javax.swing.JLabel lbconta;
    private javax.swing.JLabel lbcpf;
    private javax.swing.JLabel lbnome;
    private javax.swing.JTextField tfagencia;
    private javax.swing.JTextField tfconta;
    private javax.swing.JTextField tfnome;
    // End of variables declaration//GEN-END:variables
public static String clear(String placa){
    return placa = placa.replace("-", "").replace(".", "");
    }
public static String format (String cpf){
    int length = cpf.length();
    if(length == 11){
        cpf = cpf.substring(0,3)+"."+cpf.substring(3,6)+"."+cpf.substring(6,9)+"-"+ cpf.substring(9,11);
    }
    return cpf;
    }

}
